@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Dec 04 15:23:30 +0800 2025
REM SW Build 6233196 on Thu Sep 11 21:27:30 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_cc_behav -key {Behavioral:sim_1:Functional:tb_cc} -tclbatch tb_cc.tcl -view C:/Users/ryanh/fpga/iclab/lab1/tb_cc_behav.wcfg -log simulate.log"
call xsim  tb_cc_behav -key {Behavioral:sim_1:Functional:tb_cc} -tclbatch tb_cc.tcl -view C:/Users/ryanh/fpga/iclab/lab1/tb_cc_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
